apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page-ingress
  annotations:
    kubernetes.io/ingress.class: kom-operator
    traefik.ingress.kubernetes.io/router.entrypoints: secondary
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.hosts.landing }}
    http:
      paths:
      - backend:
          service:
            name: landing-page-service
            port:
              number: 80
        path: /
        pathType: Prefix