app:
  id: asdfghjkl
  name: Theia Blueprint
  logo: theiablueprint.png

issuer:
  email: jfaltermeier@eclipsesource.com

image:
  name: theiacloud/theia-cloud-demo:0.8.0.MS7
  pullSecret: ""
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "30"

hosts:
  service: service.<EXTERNAL-IP>.nip.io
  serviceProtocol: https
  landing: theia.cloud.<EXTERNAL-IP>.nip.io
  instance: ws.<EXTERNAL-IP>.nip.io

landingPage:
  image: theiacloud/theia-cloud-landing-page:0.8.0.MS7
  appDefinition: "theia-cloud-demo"
  # If set to true no persisted storage is used when creating sessions on the landing page.
  # Set to false if you want to use persisted storage.
  ephemeralStorage: false

keycloak:
  enable: true
  authUrl: "https://keycloak.<EXTERNAL-IP>.nip.io/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "publicbutoauth2proxywantsasecret"
  cookieSecret: "zBh3rYbeh8K1za_029Qsm3fpb7qvfz1s7fiVMWOgEhs="

operator:
  image: theiacloud/theia-cloud-operator:0.8.0.MS7
  eagerStart: false
  # Currently this is needed to use the default storage class for persistent volume claims.
  # See issue https://github.com/eclipsesource/theia-cloud/issues/92 to rework this.
  cloudProvider: "GKE"
  bandwidthLimiter: "K8SANNOTATION"
  sessionsPerUser: "1"

service:
  image: theiacloud/theia-cloud-service:0.8.0.MS7

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false
