imagePullPolicy: Always

app:
  id: asdfghjkl123
  name: Theia Blueprint

issuer:
  email: jfaltermeier@eclipsesource.com

image:
  name: theiacloud/theia-cloud-demo:0.8.1.MS1
  pullSecret: ""
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "30"
  imagePullPolicy: IfNotPresent

hosts:
  usePaths: true
  paths:
    baseHost: my-ip.nip.io
    service: servicex
    landing: theiacloud
    instance: instances

landingPage:
  image: theiacloud/theia-cloud-try-now-page:0.8.1.MS1
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: true
  additionalApps:
    coffee-editor:
      label: "Renamed Coffee Editor"
    cdt-cloud-demo:
      label: "Renamed CDT.cloud Blueprint"

keycloak:
  enable: true
  authUrl: "https://keycloak.34.141.62.32.nip.io/"
  keycloakRealm: "TheiaCloud"
  keycloakClientId: "theia-cloud"
  clientSecret: "publicbutoauth2proxywantsasecret"
  cookieSecret: "s-p4GxfRlPa_BI1XsLuvE2ihNOqYD1vmewWcXcpYjr0="

operator:
  eagerStart: false
  bandwidthLimiter: "WONDERSHAPER"
  sessionsPerUser: "3"

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false

monitor:
  enable: false
  activityTracker:
    enable: false
