extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin-password
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    acme.cert-manager.io/http01-edit-in-place: "true"
    # Should be the same as in the theia cloud values
    cert-manager.io/cluster-issuer: letsencrypt-prod
  rules:
    - host: keycloak.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - keycloak.example.com
      secretName: keycloak-cert-secret