name: Publish Demos CI

on:
  workflow_dispatch:
    inputs:
      publish_theia_cloud_demo:
        description: "Publish theia-cloud-demo?"
        type: boolean
        required: true
      publish_theia_cloud_activity_demo_theia:
        description: "Publish theia-cloud-activity-demo-theia?"
        type: boolean
        required: true
      publish_theia_cloud_activity_demo:
        description: "Publishtheia-cloud-activity-demo?"
        type: boolean
        required: true

jobs:
  publish-theia-cloud-demo:
    if: inputs.publish_theia_cloud_demo == true
    uses: ./.github/workflows/reusable-demo.yml
    with:
      docker_org: theiacloud
      docker_image: theia-cloud-demo
      docker_file: demo/dockerfiles/demo-theia-docker/Dockerfile
      docker_location: demo/dockerfiles/demo-theia-docker/.
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  publish-theia-cloud-activity-demo-theia:
    if: inputs.publish_theia_cloud_activity_demo_theia == true
    uses: ./.github/workflows/reusable-demo.yml
    with:
      docker_org: theiacloud
      docker_image: theia-cloud-activity-demo-theia
      docker_file: demo/dockerfiles/demo-theia-monitor-theia/Dockerfile
      docker_location: .
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  publish-theia-cloud-activity-demo:
    if: inputs.publish_theia_cloud_activity_demo == true
    needs: publish-theia-cloud-demo
    uses: ./.github/workflows/reusable-demo.yml
    with:
      docker_org: theiacloud
      docker_image: theia-cloud-activity-demo
      docker_file: demo/dockerfiles/demo-theia-monitor-vscode/Dockerfile
      docker_location: demo/dockerfiles/demo-theia-monitor-vscode/.
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
